services:
  table-db:
    image: postgres:16
    env_file:
      - ./table-availability/.env.docker
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U table_user -d table_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - table-db-data:/var/lib/postgresql/data

  reservation-db:
    image: postgres:16
    env_file:
      - ./reservation/.env.docker
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reservation_user -d reservation_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - reservation-db-data:/var/lib/postgresql/data

  table-service:
    build:
      context: ./table-availability
    ports:
      - "3000:3000"
    env_file:
      - ./table-availability/.env.docker
    depends_on:
      table-db:
        condition: service_healthy

  reservation-service:
    build:
      context: ./reservation
    ports:
      - "3001:3000"
    env_file:
      - ./reservation/.env.docker
    depends_on:
      reservation-db:
        condition: service_healthy
      table-service:
        condition: service_started

volumes:
  table-db-data:
  reservation-db-data: